DBC:
 Status: "ON" #ON代表有DBC文件 / OFF代表没有DBC文件(此时需要填写 ACAN.yaml 和 ECAN.yaml)
 Name: pix_plk_self_driving_1.0_20230220.dbc

Control: [0x130, 0x131, 0x132]  #控制报文的ID组
FeedBack: [0x530, 0x532, 0x534] #反馈报文的ID组

#动作集合
Action:
 Advance: [{ACU_ChassisBrakeEn: 0},{ACU_ChassisDriverEnCtrl: 1},{ACU_ChassisDriverModeCtrl: 0},{ACU_ChassisGearCtrl: 1},{ACU_ChassisSpeedCtrl: "variate"}]
 Left: [{ACU_ChassisSteerEnCtrl: 1},{ACU_ChassisSteerModeCtrl: 0},{ACU_ChassisSteerAngleTarget: "variate"}]
 Right: [{ACU_ChassisSteerEnCtrl: 1},{ACU_ChassisSteerModeCtrl: 0},{ACU_ChassisSteerAngleTarget: "variate"}]
 Back: [{ACU_ChassisBrakeEn: 0},{ACU_ChassisDriverEnCtrl: 1},{ACU_ChassisDriverModeCtrl: 0},{ACU_ChassisGearCtrl: 3},{ACU_ChassisSpeedCtrl: "variate"}]
 Stop: [{ACU_ChassisBrakeEn: 0},{ACU_ChassisDriverEnCtrl: 1},{ACU_ChassisDriverModeCtrl: 0},{ACU_ChassisGearCtrl: 1},{ACU_ChassisSpeedCtrl: 0}]
 AEB: [{ACU_ChassisBrakeEn: 1},{ACU_ChassisBrakePdlTarget: 50}]
 HeadLight: []
 LeftLight: []
 RightLight: []
 BackLight: []

#车辆参数
VehicleParam:
 WheelBase: 1.5

 
#-------------------------------------------------------------------------------------------------------------
Heart: [{SignalName: ACU_DriveLifeSig, scope: [0,15]},
        {SignalName: ACU_BrakeLifeSig, scope: [0,15]},
        {SignalName: ACU_SteerLifeSig, scope: [0,15]}]

Check: [{SignalName: ACU_CheckSum_130, byte: [0,1,2,3,4,5,6], mode: xor},
        {SignalName: ACU_CheckSum_131, byte: [0,1,2,3,4,5,6], mode: xor},
        {SignalName: ACU_CheckSum_132, byte: [0,1,2,3,4,5,6], mode: xor}]